### ISSUE TITLE
Can we use GPT4o mini?

### ISSUE THREAD

**Issue by nasko94** [skapadia3214/groq-moa#3]
I would like a way to use GPT4o mini

**Comment by Kaushalsurana** [comment]
I think it would greatly reduce the speed of the agents. Since we are using 3-4 agents in different layer , GPT would make the response really slow . It is thank to groq we are getting the output so quickly

**Comment by PeterDaveHello** [comment]
Could GPT-4o mini still be fast? There might be speed differences with more powerful models on groq.
